# Generated by Django 4.1.7 on 2023-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Profile',
            fields=[
                ('profile_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('profile_name', models.CharField(default='Pharma', max_length=45)),
                ('in_file_path', models.TextField()),
                ('out_file_path', models.TextField()),
                ('archieve_path', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=50, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
